local_development: False
use_valon: True

sensors:   
    ADC_1:
      name: ADS1115
      connection:
        type: I2C
        parameters:
          mode: differential
          channels: [[0,1]]
          output: value
      sensor_info:
          type: ADC
          manufacturer: ADS
      configuration: 
        gain: 8
        data_rate: 128

source:
  name: VALON-5019
  port: /dev/VALON
  baudrate: 9600
  freq: 90
  power: 4
  mod_amp: 15
  mod_freq: 0

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI