local_development: False

sensors:   
    ADC_1:
      name: ADS1115
      connection:
        type: I2C
        parameters:
          mode: differential
          channels: [[0,1]]
          output: voltage
      sensor_info:
          type: ADC
          manufacturer: ADS
      configuration: 
        gain: 16
        data_rate: 250

source:
  name: VALON-5019
  port: /dev/VALON
  baudrate: 9600
  freq: 90
  power: -4
  mod_amp: 16
  mod_freq: 47

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI
