local_development: False

sensors:   
  ADC_1:
    name: ADS1015
    connection:
      type: I2C
      parameters:
        bus: 6
        address: 0x48
        mode: differential
        channels: [0,1]
        output: voltage
    sensor_info:
        type: ADC
        manufacturer: ADS
    configuration: 
      gain: 16
      adc_rate: 490
      
  DAC_1:
    name: MCP4725
    connection:
      type: I2C
      parameters:
        address: 0x60
    sensor_info:
        type: DAC
        manufacturer: ADS
    configuration: 
      voltage: 1.1
      max_voltage: 3.3
      
source:
  name: VALON-5019
  port: /dev/ttyAMA4
  baudrate: 115200
  freq: 90
  power: -6.5
  mod_amp: 15
  mod_freq: 37
  mult_factor: 6

