local_development: False

camera:
  name: Sony
  mode: video
  program: MovieM
  duration: 20
  ISO: 1600
  shutter_speed: 0.001
  focus_distance: infinity

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI
