local_development: False

sensors:
    GPS_1:
      name: ZED-F9P
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA0
          baudrate: 115200
      sensor_info:
        type: GPS
        manufacturer: UBlox
      configuration:
        NMEA1:
          output:
            port: UART1
            set: True
        NMEA2:
          output:
            port: UART2
            set: False
        UBX:
          output:
            port: UART1
            set: True
        RATE:
          value: 1
        UBX_MSG:
          output_port: UART1
          NAV: [
            'POSECEF',
            'POSLLH'
            ]
          RXM: [
            'RAWX',
            'SFRBX'
            ]
        NMEA_MSG:
          output_port: UART2
          ID : [
            'GGA',
            'GSV',
            'GSA',
            'GST',
            'GNS',
            'ZDA'
          ]

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI
