local_development: False

sensors:
    GPS_1:
      name: ZED-F9P
      connection:
        type: serial
        parameters:
          port: /dev/AMA0
          baudrate: 115200
      sensor_info:
        type: GPS
        manufacturer: UBlox
      configuration:
        NMEA:
          output:
            port: UART1
            set: False
        UBX:
          output:
            port: USB
            set: True
        RATE:
          value: 1
        UBX_MSG:
          output_port: USB
          NAV: [
            'POSECEF',
            'POSLLH'
            ]
          RXM: [
            'RAWX',
            'SFRBX'
            ]

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI
