local_development: False

sensors:
    Inclinometer_1:
      name: Kernel-100
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA3
          baudrate: 115200
      sensor_info:
        type: Inclinometer
        manufacturer: Inertial_Labs
      configuration:
        mode: KERNEL_CalibHR

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI
