local_development: False
sensors:
    Inclinometer_1:
      name: Kernel-100
      connection:
        type: serial
        parameters:
          port: /dev/inclinometer
          baudrate: 115200
      sensor_info:
        type: Inclinometer
        manufacturer: Inertial_Labs
      configuration:
        mode: KERNEL_CalibHR
    
    ADC_1:
      name: ADS1115
      connection:
        type: I2C
        parameters:
          mode: differential
          channels: [[0,1]]
          output: value
      sensor_info:
          type: ADC
          manufacturer: ADS
      configuration: 
        gain: 8
        data_rate: 128
    
    DAC_1:
      name: MCP4725
      connection:
        type: I2C
        parameters:
          address: 0x60
      sensor_info:
          type: DAC
          manufacturer: ADS
      configuration: 
        voltage: 0.8
        max_voltage: 3.3

source:
  name: VALON-5019
  port: /dev/VALON
  baudrate: 9600
  freq: 90
  power: 4
  mod_amp: 15
  mod_freq: 0

telemetry:
  enabled: False
  antenna:
    name: XBEE3
    type: XBEE
    port: /dev/XBEE
    baudrate: 38400
    remote: OBI