local_development: False


sensors:
    GPS_1:
      name: ZED-F9P
      file_name: ""
      sensor_core: 3
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA0
          baudrate: 115200
      sensor_info:
        type: GPS
        manufacturer: UBlox
      configuration:
        NMEA1:
          output:
            port: UART1
            set: False
        NMEA2:
          output:
            port: UART2
            set: True
        UBX:
          output:
            port: UART1
            set: True
        RATE:
          value: 2
        UBX_MSG:
          output_port: UART1
          NAV: [
            'POSECEF',
            'POSLLH',
            'CLOCK'
            ]
          RXM: [
            'RAWX',
            'SFRBX'
            ]
        NMEA_MSG:
          output_port: UART2
          ID : [
            'GGA',
            'GSV',
            'GSA',
            'GST',
            'GNS',
            'ZDA'
          ]
    
    ADC_1:
      name: ADS1015
      sensor_core: 3
      connection:
        type: I2C
        parameters:
          bus: 6
      sensor_info:
          type: ADC
          manufacturer: ADS
      configuration: 
        gain: 2
        data_rate: 1600

    INERTIAL_1:
      name: Inertial
      sensor_core: 2
      connection:
        type: I2C
        parameters:
          bus: 4
      sensor_info:
          type: Inertial
          manufacturer: Varios
      configuration: 
        data_rate: 200
