local_development: False

camera:
  name: Sony
  mode: video
  program: MovieM
  ISO: 100
  shutter_speed: 0.000625
  focus_distance: infinity

source:
  name: VALON-5019
  port: /dev/ttyAMA4
  baudrate: 115200
  freq: 93
  power: -6.5
  mod_amp: 15
  mod_freq: 37
  mult_factor: 6

sensors:
    GPS_1:
      name: ZED-F9P
      sensor_core: 3
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA0
          baudrate: 115200
      sensor_info:
        type: GPS
        manufacturer: UBlox
      configuration:
        NMEA1:
          output:
            port: UART1
            set: False
        NMEA2:
          output:
            port: UART2
            set: True
        UBX:
          output:
            port: UART1
            set: True
        RATE:
          value: 2
        UBX_MSG:
          output_port: UART1
          NAV: [
            'POSECEF',
            'POSLLH',
            'CLOCK'
            ]
          RXM: [
            'RAWX',
            'SFRBX'
            ]
        NMEA_MSG:
          output_port: UART2
          ID : [
            'GGA',
            'GSV',
            'GSA',
            'GST',
            'GNS',
            'ZDA'
          ]
    
    ADC_1:
      name: ADS1015
      sensor_core: 3
      connection:
        type: I2C
        parameters:
          bus: 6
      sensor_info:
          type: ADC
          manufacturer: ADS
      configuration: 
        gain: 16
        data_rate: 1600

    DAC_1:
      name: MCP4725
      connection:
        type: I2C
        parameters:
          bus: 1
          address: 0x60
      sensor_info:
          type: DAC
          manufacturer: MCP
      configuration: 
        voltage: 1.02
        max_voltage: 3.3

    INERTIAL_1:
      name: Inertial
      sensor_core: 2
      connection:
        type: I2C
        parameters:
          bus: 4
      sensor_info:
          type: Inertial
          manufacturer: Varios
      configuration: 
        data_rate: 200
        
    Inclinometer_1:
      name: Kernel-100
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA5
          baudrate: 230400
      sensor_info:
        type: Inclinometer
        manufacturer: Inertial_Labs
      configuration:
         mode: KERNEL_CalibHR
