local_development: False

camera:
  name: Sony
  mode: photo
  program: Photo_Auto
  fps: 1
  max_frame: 20

sensors:
    Inclinometer_1:
      name: Kernel-100
      connection:
        type: serial
        parameters:
          port: /dev/inclinometer
          baudrate: 115200
      sensor_info:
        type: Inclinometer
        manufacturer: Inertial_Labs
      configuration:
        mode: KERNEL_CalibHR