local_development: False
use_valon: False

camera:
  name: Sony
  mode: video
  program: Video_Auto
  duration: 10

sensors:
    Inclinometer_1:
      name: Kernel-100
      connection:
        type: serial
        parameters:
          port: /dev/inclinometer
          baudrate: 115200
      sensor_info:
        type: Inclinometer
        manufacturer: Inertial_Labs
      configuration:
        mode: KERNEL_CalibHR