local_development: False

#camera:
  #name: Sony
  #mode: video
  #program: MovieM
  #ISO: 100
  #shutter_speed: 0.001
  #focus_distance: infinity

camera:
   name: Alvium
   framerate: 5
   mode: trigger
   core: 3


