global:
  name: porter
  version: 4.0
  description: Telemetry configuration for Porter
  autostart_camera: True
  autostart_poi_tracking: False

sensors:
  GPS_1:
    name: ZED-F9P
    sensor_core: 3
    connection:
      type: serial
      parameters:
        port: /dev/ttyAMA0
        baudrate: 115200
    sensor_info:
      type: GPS
      manufacturer: UBlox
    configuration:
        NMEA1:
          output:
            port: UART1
            set: False
        UBX:
          output:
            port: UART1
            set: True
        RATE:
          value: 2
        UBX_MSG:
          output_port: UART1
          NAV: [
            'POSECEF',
            'POSLLH',
            'CLOCK',
            'STATUS' # this is needed to get the fix status
            ]
          RXM: [
            'RAWX',
            'SFRBX'
            ]
        NMEA_MSG:
          output_port: UART2
          ID : [
            'RMC',
            'GST'
          ]
  
  ADC_1:
    name: ADS1015
    sensor_core: 1
    connection:
      type: I2C
      parameters:
        bus: 4
        address: 0x48
    sensor_info:
        type: ADC
        manufacturer: ADS
    configuration: 
      gain: 16
      data_rate: 1600

  IMX5_1:
      name: IMX5-Sensors
      sensor_core: 2
      connection:
        type: serial
        parameters:
          device: /dev/ttyACM0
          baudrate: 921600
      sensor_info:
        type: IMX5
        manufacturer: InertialSense
      configuration:
        imu_data_rate: 1000
        ins_data_rate: 142

  DAC_1:
    name: MCP4725
    connection:
      type: I2C
      parameters:
        bus: 1
        address: 0x60
    sensor_info:
        type: DAC
        manufacturer: MCP
    configuration: 
      voltage: 2.0
      max_voltage: 3.3

  INERTIAL_1:
    name: Inertial
    sensor_core: 2
    connection:
      type: I2C
      parameters:
        bus: 3
    sensor_info:
        type: Inertial
        manufacturer: Varios
    configuration: 
      data_rate: 150

camera:
  name: Alvium
  core: 3
  exposure: 5000
  gain: 0.0
  format: BayerRG8
  max_framerate: 5
  writing_threads: 2
  verbosity: False


pointing_controller:
  name: lager
  gimbal:
    name: Gremsy T7
    simulator: False
    connection:
      type: serial
      protocol: mavlink
      port: /dev/ttyAMA3
      baudrate: 115200
      timeout: 3
    telemetry:
      heartbeat_frequency: 1  # Hz
      frequency: 50  # Hz

  poi:
    name: POI
    latitude: 50.9601079
    longitude: -1.8971433
    altitude: 139
    max_distance: 1000.0  # meters

status_writer:
  enabled: True
  update_rate: 1


#power_monitor:
#  name: INA228
#  connection:
#    type: I2C
#    parameters:
#      bus: 6
#      address: 0x40
#  sensor_info:
#      type: Power Monitor
#      manufacturer: Adafruit
#  configuration:
#    gain: 8
#    data_rate: 1600