local_development: False


sensors:
    IMX5_1:
      name: IMX5-Sensors
      sensor_core: 1
      connection:
        type: serial
        parameters:
          device: /dev/ttyAMA5
          baudrate: 115200
      sensor_info:
        type: IMX5
        manufacturer: InertialSense
      configuration:
        imu_data_rate: 1000
        ins_data_rate: 142
