local_development: False


sensors:
    IMX5_1:
      name: IMX5-Sensors
      sensor_core: 1
      connection:
        type: serial
        parameters:
          usb_device: /dev/ttyACM0
      sensor_info:
        type: IMX5
        manufacturer: Parker
      configuration:
        imu_data_rate: 1000
        ins_data_rate: 142
