local_development: False

sensors:
    GPS_1:
      name: ZED-F9P
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA0
          baudrate: 115200
      sensor_info:
        type: GPS
        manufacturer: UBlox
      configuration:
        NMEA1:
          output:
            port: UART1
            set: False
        NMEA2:
          output:
            port: UART2
            set: True
        UBX:
          output:
            port: UART1
            set: True
        RATE:
          value: 2
        UBX_MSG:
          output_port: UART1
          NAV: [
            'POSECEF',
            'POSLLH'
            ]
          RXM: [
            'RAWX',
            'SFRBX'
            ]
        NMEA_MSG:
          output_port: UART2
          ID : [
            'GGA',
            'GSV',
            'GSA',
            'GST',
            'GNS',
            'ZDA'
          ]

    Inclinometer_1:
      name: Kernel-100
      connection:
        type: serial
        parameters:
          port: /dev/ttyAMA5
          baudrate: 115200
      sensor_info:
        type: Inclinometer
        manufacturer: Inertial_Labs
      configuration:
        mode: KERNEL_CalibHR
    
    ADC_1:
      name: ADS1015
      connection:
        type: I2C
        parameters:
          bus: 6
          address: 0x48
          mode: differential
          channels: [0,1]
      sensor_info:
          type: ADC
          manufacturer: ADS
      configuration: 
        gain: 16
        adc_rate: 1600
        reading_rate: 350
        
dac:
  name: MCP4725
  connection:
    type: I2C
    parameters:
      bus: 1
      address: 0x60
  configuration: 
    voltage: 1.8
    max_voltage: 3.3

source:
  name: VALON-5019
  port: /dev/ttyAMA4
  baudrate: 115200
  freq: 90
  power: -6.5
  mod_amp: 15
  mod_freq: 37
  mult_factor: 6

